"""Canonical skill phrases for resume / job text matching (case-insensitive)."""
SKILL_LEXICON = [
    "machine learning",
    "deep learning",
    "data science",
    "computer vision",
    "natural language processing",
    "nlp",
    "large language model",
    "llm",
    "generative ai",
    "tensorflow",
    "pytorch",
    "keras",
    "scikit-learn",
    "sklearn",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "plotly",
    "sql",
    "postgresql",
    "mysql",
    "mongodb",
    "redis",
    "spark",
    "pyspark",
    "hadoop",
    "kafka",
    "airflow",
    "docker",
    "kubernetes",
    "ci/cd",
    "mlops",
    "aws",
    "azure",
    "gcp",
    "google cloud",
    "python",
    "r programming",
    "java",
    "scala",
    "c++",
    "javascript",
    "typescript",
    "react",
    "node.js",
    "nodejs",
    "fastapi",
    "flask",
    "django",
    "rest api",
    "graphql",
    "statistics",
    "probability",
    "a/b testing",
    "experimentation",
    "feature engineering",
    "model deployment",
    "transformers",
    "hugging face",
    "opencv",
    "xgboost",
    "lightgbm",
    "reinforcement learning",
    "time series",
    "etl",
    "data engineering",
    "big data",
    "tableau",
    "power bi",
    "git",
    "linux",
    "agile",
]
